language: node_js
node_js:
# - "0.12"
# - "0.11"
- '0.10'
env:
- BUILDER="52.6.42.144" PROJECT="node-hello" AUTH="Basic bWlzZml0OlVzZXJAMTIz"

before_install:
- npm install -g mocha istanbul
# install:
# - npm install
# no after_install

# before_script:
# - git describe --always --tags --long
# - git rev-parse --abbrev-ref HEAD
script:
- istanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly -- -R spec
- 'curl -X PUT -H "Authorization: ${AUTH}" -H "Content-Type: application/json" -d "{\"branch\":\"${TRAVIS_BRANCH}\",\"build_num\":\"${TRAVIS_JOB_NUMBER}\"}" "http://${BUILDER}/${PROJECT}/build" -m 3600000'
# after_success:
# - echo "success"
# after_failure:
# - echo "failure"
after_script:
# - echo "after script"
- cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
- rm -rf ./coverage

# before_deploy:
# - echo "defore deploy"
deploy:
  provider: heroku
  app: forhot2000-node-hello
  api_key:
    secure: m8XIXcUtSW/Da5QTLUoBjReIptHQANjj0BVS5AKYx1/2QyjfwDFLBEWs5lcvKjwCwTqvK1nAlS/pcNMVwExK6wH2VM0a7HDi561LF8ZTmeQsxh49qfQdZPgqoSrHSR1JTxkyOM1uKljqZ6wQC5z4qft+8Bd86mDVIBtfMebAD1Q=
  # default only deply master branch
after_deploy:
# - echo "after deploy"
# - curl https://forhot2000-node-hello.herokuapp.com/
- echo "open https://forhot2000-node-hello.herokuapp.com/ in browser"

branches:
  only:
  - master
  - develop
cache:
  directories:
  - node_modules
notifications:
  hipchat: C5Ta9DcFxSNftnD2ZMtfRJN2SbUtRLuGDQy6JXmI@1467331
