sudo: required
language: node_js
node_js:
  - "0.10"
  - "0.8"
before_install:
  - wget -qO- https://get.docker.com/ | sh
  - sudo docker version
install:
  - npm install -g mocha istanbul
  - npm install
script:
  - npm start
