language: node_js
node_js:
  - "0.12"
  - "0.11"
  - "0.10"
install:
  - npm install -g mocha istanbul
  - npm install
script:
  - git describe --always --tags --long
  - git rev-parse --abbrev-ref HEAD
  - npm test
