language: node_js
node_js:
  - "0.10"
env:
  global:
    - WORK_PROCESSES=2
  matrix:
    - NODE_ENV=staging
    - NODE_ENV=production
before_install:
  - wget -qO- https://get.docker.com/ | sh
  - sudo docker version
install:
  - npm install -g mocha istanbul
  - NODE_ENV=development npm install
script:
  - npm start
after_success:
  - echo "NODE_ENV=$NODE_ENV WORK_PROCESSES=$WORK_PROCESSES AWS_KEY=$AWS_KEY"
