language: node_js
node_js:
  # - "0.12"
  # - "0.11"
  - "0.10"
install:
  - npm install -g mocha istanbul
  - npm install
script:
  - git describe --always --tags --long
  - git rev-parse --abbrev-ref HEAD
  - istanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly -- -R spec && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
