language: node_js
node_js: '0.10' 

before_install:
  - npm install -g mocha istanbul

before_script:
  - curl http://$ARES_SERVER/downloads/ares-linux-386.tar.gz | tar xzv

script:
  - istanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly -- -R spec
  - ./ares

after_script:
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
  - rm -rf ./coverage

# deploy:
#   provider: heroku
#   app: westmisfit-node-hello
#   api_key:
#     secure: m8XIXcUtSW/Da5QTLUoBjReIptHQANjj0BVS5AKYx1/2QyjfwDFLBEWs5lcvKjwCwTqvK1nAlS/pcNMVwExK6wH2VM0a7HDi561LF8ZTmeQsxh49qfQdZPgqoSrHSR1JTxkyOM1uKljqZ6wQC5z4qft+8Bd86mDVIBtfMebAD1Q=
# after_deploy:
#   - curl https://westmisfit-node-hello.herokuapp.com/
#   - echo "open https://westmisfit-node-hello.herokuapp.com/ in browser"

branches:
  only:
    - master
    - develop

cache:
  directories:
    - node_modules

notifications:
  hipchat: C5Ta9DcFxSNftnD2ZMtfRJN2SbUtRLuGDQy6JXmI@1467331
